### ISSUE TITLE
API endpoint for new subscribers 

### ISSUE THREAD

**Issue by samui68400** [kopy-kat/friend-tech-api#1]
I saw some discord channels which built a live feed that gives informations about the new subscribers in real time. Do you have any method or an endpoint to get it?

**Comment by kopy-kat** [comment]
I haven't found an endpoint for this. One common way of doing this is looking at the contract and watching for first buys of a token. However, what some bots have also been doing is even look at the ETH-Base bridge and using that to guess that a user is joining friend tech (to insta-buy the token).

**Comment by samui68400** [comment]
tx for your answer

**Comment by JeffXu1** [comment]
hi, do you find the endpoint for new subscribers now? Thanks!

**Comment by kopy-kat** [comment]
Hey, sadly no endpoint found that is exposed to the public

**Comment by BrokedTV** [comment]
There is definitely one or a way to get them because there are feeds out there that show user that joins even when they address balance is still zero. Still haven't found how.
